#!/usr/bin/env zsh

command -v brew > /dev/null 2>&1 || {
  echo >&2 ""
  echo >&2 "ERROR: Executable 'brew' not found."
  echo >&2 ""
  echo >&2 "Use use the following command to install it:"
  echo >&2 '/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"'
  echo >&2 ""
  echo >&2 "Then re-run:"
  echo >&2 "$0"
  exit 1
}

brew install 1password
brew install alacritty
brew install amethyst
brew install balenaetcher
brew install boop
brew install brave-browser
brew install docker
brew install dotnet-sdk
brew install electrum
brew install firefox
brew install font-code-new-roman-nerd-font
brew install font-fira-code
brew install font-fira-code-nerd-font
brew install font-hack-nerd-font
brew install font-hasklug-nerd-font
brew install font-iosevka-nerd-font
brew install font-jetbrains-mono-nerd-font
brew install font-meslo-lg-nerd-font
brew install font-monoid-nerd-font
brew install font-noto-nerd-font
brew install font-powerline-symbols
brew install font-roboto-mono
brew install font-roboto-mono-nerd-font
brew install font-sauce-code-pro-nerd-font
brew install font-victor-mono-nerd-font
brew install forklift
brew install genymotion
brew install google-chrome
brew install hammerspoon
brew install hyper
brew install ibackup-viewer
brew install karabiner-elements
brew install kitty
brew install macdown
brew install min
brew install postman
brew install sizeup
brew install skype
brew install virtualbox
brew install visual-studio-code
brew install vv
brew install wezterm
brew install adoptopenjdk/openjdk/adoptopenjdk11
brew install adoptopenjdk/openjdk/adoptopenjdk8
brew install microsoft/git/git-credential-manager-core
brew install angular-cli
brew install bash-completion@2
brew install ccls
brew install clang-format
brew install cmake
brew install cowsay
brew install csvkit
brew install deno
brew install diff-so-fancy
brew install docker
brew install eth-p/software/bat-extras
brew install exa
brew install exercism
brew install fd
brew install figlet
brew install fish
brew install flow
brew install fzf
brew install fzy
brew install ghc
brew install glow
brew install gnupg
brew install gping
brew install grip
brew install haskell-stack
brew install hlint
brew install htop
brew install http-server
brew install ipython
brew install jq
brew install libvterm
brew install lolcat
brew install lua-language-server
brew install luajit
brew install luarocks
brew install macos-trash
brew install macvim
brew install maven
brew install maven-completion
brew install mmv
brew install most
brew install neofetch
brew install neovim
brew install noti
brew install nushell
brew install openapi-generator
brew install perltidy
brew install ponysay
brew install python@3.8
brew install r
brew install railwaycat/emacsmacport/emacs-mac
brew install ranger
brew install rlwrap
brew install rust-analyzer
brew install rustup-init
brew install sbcl
brew install scipy
brew install sdl2
brew install shellcheck
brew install shellharden
brew install showkey
brew install starship
brew install stylua
brew install subversion
brew install texlab
brew install thefuck
brew install tldr
brew install tmux
brew install tmux-mem-cpu-load
brew install unrar
brew install w3m
brew install webkit2png
brew install wget
brew install zplug
brew install zsh-completions
