command_timeout = 10000
[env_var]
variable = "STARSHIP_SHELL"
default = "unknown"
style = "blue bold"
format = "with [${env_value}]($style) "

[docker_context]
disabled = "false"
only_with_files = "true"

[rlang]
disabled = "true"
detect_files = []
