# vim: set ft=kitty.conf syntax=config:

## FiraCode START ##
#
font_family FiraCode Nerd Font Mono
bold_font FiraCode Nerd Font Mono Bold
italic_font JetBrains Mono Medium Italic
bold_italic_font JetBrains Mono Bold Italic
font_features FiraCodeNerdFontCompleteM-Retina +zero +onum
# adjust_line_height 98%
adjust_column_width 98%
#
## FiraCode END ##
