# vim: set ft=kitty.conf syntax=config:

## FiraCode START ##
#
font_family FiraCode Nerd Font
bold_font Fira Code Bold Nerd Font
italic_font Fira Code Italic Nerd Font
bold_italic_font Fira Code Bold Italic Nerd Font
font_features FiraCodeNerdFontCompleteM-Retina +zero +onum
adjust_line_height 80%
adjust_column_width 98%
#
## FiraCode END ##
