# vim: set ft=kitty.conf syntax=config:

## FiraCode START ##
#
font_family FiraCode Nerd Font Mono
bold_font FiraCode Nerd Font Mono Bold
font_features FiraCodeNerdFontCompleteM-Retina +zero +onum
adjust_line_height 90%
adjust_column_width 98%
#
## FiraCode END ##
