# vim: set ft=kitty.conf syntax=config:
#
include gruvbox.conf

allow_remote_control yes

font_family Fira Code
bold_font Fira Code SemiBold
italic_font Fira Code Italic
bold_italic_font Fira Code SemiBold Italic

font_size 18.0
symbol_map U+E0A0-U+E0A3,U+E0C0-U+E0C7 PowerlineSymbols

shell /bin/zsh --login
editor .

background_opacity 0.8

remember_window_size  yes
initial_window_width  1280
initial_window_height 900

hide_window_decorations yes

window_margin_width 5.0
single_window_margin_width 5.0
window_padding_width 10.0
window_border_width 2.5

map ctrl+shift+up neighboring_window up
map ctrl+shift+down neighboring_window down

draw_minimal_borders no
active_border_color #98971a
inactive_border_color #928374

tab_bar_style powerline
tab_bar_margin_width 5.0
tab_bar_min_tabs 1
tab_bar_edge bottom
tab_fade 0.25 0.5 0.75 1
tab_bar_background #585858
active_tab_foreground   #171717
active_tab_background   #969696
active_tab_font_style   bold
inactive_tab_foreground #282828
inactive_tab_background #787878
inactive_tab_font_style bold
