# ============================================================================
# Standard Profile Package Manifest
# ============================================================================
#
# Recommended packages for most developers
# Focuses on: common tools, modern CLI replacements, essential dev tools
#
# Generated for dotfiles profile: standard
# Compatible with: macOS (brew), Ubuntu/Debian (apt), Windows (choco)
# ============================================================================

version: "1.0"

metadata:
  name: "Standard Profile Packages"
  description: "Recommended packages for balanced development environment"
  profile: standard
  last_updated: "2025-10-15"
  compatible_systems:
    - macos
    - ubuntu
    - debian

settings:
  skip_installed: true
  auto_confirm: false

# ============================================================================
# Packages
# ============================================================================

packages:
  # ============================================================================
  # Essential Tools (from minimal profile)
  # ============================================================================

  - id: git
    name: "Git"
    description: "Distributed version control system"
    category: vcs
    priority: required
    install:
      brew: git
      apt: git
      choco: git

  - id: curl
    name: "cURL"
    description: "Command line HTTP client"
    category: network
    priority: required
    install:
      brew: curl
      apt: curl
      choco: curl

  - id: wget
    name: "Wget"
    description: "Network downloader"
    category: network
    priority: required
    install:
      brew: wget
      apt: wget
      choco: wget

  - id: neovim
    name: "Neovim"
    description: "Modern Vim-based editor"
    category: editor
    priority: required
    install:
      brew: neovim
      apt: neovim
      choco: neovim

  - id: zsh
    name: "Z Shell"
    description: "Modern shell with powerful features"
    category: shell
    priority: required
    install:
      brew: zsh
      apt: zsh
      choco: zsh

  - id: tmux
    name: "Tmux"
    description: "Terminal multiplexer"
    category: terminal
    priority: recommended
    install:
      brew: tmux
      apt: tmux
      choco: tmux

  # ============================================================================
  # Modern CLI Replacements
  # ============================================================================

  - id: ripgrep
    name: "ripgrep"
    description: "Fast grep alternative written in Rust"
    category: search
    priority: recommended
    install:
      brew: ripgrep
      apt: ripgrep
      choco: ripgrep

  - id: fd
    name: "fd"
    description: "Fast find alternative written in Rust"
    category: search
    priority: recommended
    install:
      brew: fd
      apt: fd-find
      choco: fd

  - id: bat
    name: "bat"
    description: "Cat clone with syntax highlighting"
    category: utilities
    priority: recommended
    install:
      brew: bat
      apt: bat
      choco: bat

  - id: exa
    name: "exa"
    description: "Modern ls replacement"
    category: utilities
    priority: recommended
    install:
      brew: exa
      apt: exa
      choco: exa

  - id: fzf
    name: "fzf"
    description: "Fuzzy finder for command line"
    category: utilities
    priority: recommended
    install:
      brew: fzf
      apt: fzf
      choco: fzf

  # ============================================================================
  # Development Tools
  # ============================================================================

  - id: gh
    name: "GitHub CLI"
    description: "GitHub command line tool"
    category: vcs
    priority: recommended
    install:
      brew: gh
      apt: gh
      choco: gh

  - id: git-delta
    name: "Delta"
    description: "Syntax-highlighting pager for git"
    category: vcs
    priority: recommended
    install:
      brew: git-delta
      apt: git-delta
      choco: delta

  - id: jq
    name: "jq"
    description: "JSON processor"
    category: utilities
    priority: recommended
    install:
      brew: jq
      apt: jq
      choco: jq

  - id: tree
    name: "Tree"
    description: "Directory tree viewer"
    category: utilities
    priority: recommended
    install:
      brew: tree
      apt: tree
      choco: tree

  - id: htop
    name: "htop"
    description: "Interactive process viewer"
    category: monitoring
    priority: recommended
    install:
      brew: htop
      apt: htop
      choco: htop

  # ============================================================================
  # Language Runtimes & Package Managers
  # ============================================================================

  - id: python3
    name: "Python 3"
    description: "Python programming language"
    category: language
    priority: required
    install:
      brew: python3
      apt: python3
      choco: python3

  - id: node
    name: "Node.js"
    description: "JavaScript runtime"
    category: language
    priority: recommended
    install:
      brew: node
      apt: nodejs
      choco: nodejs

  - id: lua
    name: "Lua"
    description: "Lightweight scripting language"
    category: language
    priority: recommended
    install:
      brew: lua
      apt: lua5.4
      choco: lua

  - id: rust
    name: "Rust"
    description: "Systems programming language"
    category: language
    priority: recommended
    install:
      brew: rust
      apt: rustc
      choco: rust

  - id: go
    name: "Go"
    description: "Google's programming language"
    category: language
    priority: recommended
    install:
      brew: go
      apt: golang
      choco: golang

  # ============================================================================
  # Terminal & Shell Enhancements
  # ============================================================================

  - id: starship
    name: "Starship"
    description: "Cross-shell prompt"
    category: shell
    priority: recommended
    install:
      brew: starship
      apt: |
        curl -sS https://starship.rs/install.sh | sh -s -- -y
      choco: starship

  - id: zoxide
    name: "zoxide"
    description: "Smarter cd command"
    category: navigation
    priority: recommended
    install:
      brew: zoxide
      apt: zoxide
      choco: zoxide

  # ============================================================================
  # Build Tools
  # ============================================================================

  - id: make
    name: "Make"
    description: "Build automation tool"
    category: build
    priority: recommended
    install:
      brew: make
      apt: build-essential
      choco: make

  - id: cmake
    name: "CMake"
    description: "Cross-platform build system"
    category: build
    priority: recommended
    install:
      brew: cmake
      apt: cmake
      choco: cmake
