# ============================================================================
# Work Profile Package Manifest
# ============================================================================
#
# Professional development tools for enterprise/corporate environments
# Focuses on: Java, TypeScript/JavaScript, Python, productivity tools
#
# Generated for dotfiles profile: work
# Compatible with: macOS (brew), Ubuntu/Debian (apt), Windows (choco)
# ============================================================================

version: "1.0"

metadata:
  name: "Work Profile Packages"
  description: "Enterprise development tools and productivity packages"
  profile: work
  last_updated: "2025-10-15"
  compatible_systems:
    - macos
    - ubuntu
    - debian

settings:
  skip_installed: true
  auto_confirm: false

packages:
  # Core essentials (inherited from minimal)
  - id: git
    name: "Git"
    category: vcs
    priority: required
    install:
      brew: git
      apt: git
      choco: git

  - id: neovim
    name: "Neovim"
    category: editor
    priority: required
    install:
      brew: neovim
      apt: neovim
      choco: neovim

  # Enterprise languages
  - id: java
    name: "OpenJDK"
    description: "Java Development Kit"
    category: language
    priority: required
    install:
      brew: openjdk@17
      apt: openjdk-17-jdk
      choco: openjdk17

  - id: node
    name: "Node.js"
    description: "JavaScript runtime"
    category: language
    priority: required
    install:
      brew: node
      apt: nodejs
      choco: nodejs

  - id: python3
    name: "Python 3"
    category: language
    priority: required
    install:
      brew: python3
      apt: python3
      choco: python3

  - id: go
    name: "Go"
    category: language
    priority: recommended
    install:
      brew: go
      apt: golang
      choco: golang

  # Modern CLI tools
  - id: ripgrep
    name: "ripgrep"
    category: search
    priority: recommended
    install:
      brew: ripgrep
      apt: ripgrep
      choco: ripgrep

  - id: fd
    name: "fd"
    category: search
    priority: recommended
    install:
      brew: fd
      apt: fd-find
      choco: fd

  - id: bat
    name: "bat"
    category: utilities
    priority: recommended
    install:
      brew: bat
      apt: bat
      choco: bat

  - id: jq
    name: "jq"
    category: utilities
    priority: recommended
    install:
      brew: jq
      apt: jq
      choco: jq

  # Professional tools
  - id: gh
    name: "GitHub CLI"
    category: vcs
    priority: recommended
    install:
      brew: gh
      apt: gh
      choco: gh

  - id: maven
    name: "Maven"
    description: "Java build tool"
    category: build
    priority: recommended
    install:
      brew: maven
      apt: maven
      choco: maven

  - id: gradle
    name: "Gradle"
    description: "Build automation tool"
    category: build
    priority: recommended
    install:
      brew: gradle
      apt: gradle
      choco: gradle
