name: Sync Web Installers to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'install/dfauto'
      - 'install/dfsetup'
      - 'install/dfauto.ps1'
      - 'install/dfsetup.ps1'
  workflow_dispatch:  # Allow manual trigger

jobs:
  sync-installers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout dotfiles repository
        uses: actions/checkout@v4
        with:
          path: dotfiles

      - name: Checkout buckmeister.github.io repository
        uses: actions/checkout@v4
        with:
          repository: Buckmeister/buckmeister.github.io
          token: ${{ secrets.PAGES_DEPLOY_TOKEN }}
          path: pages

      - name: Sync installer files
        run: |
          # Copy installers from dotfiles to GitHub Pages
          cp dotfiles/install/dfauto pages/dfauto
          cp dotfiles/install/dfsetup pages/dfsetup
          cp dotfiles/install/dfauto.ps1 pages/dfauto.ps1
          cp dotfiles/install/dfsetup.ps1 pages/dfsetup.ps1

          # Set executable permissions for Unix scripts
          chmod +x pages/dfauto pages/dfsetup

          echo "Installer files synced successfully"

      - name: Check for changes
        id: check_changes
        run: |
          cd pages
          if git diff --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
            echo "No changes to commit"
          else
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "Changes detected:"
            git diff --stat
          fi

      - name: Commit and push to buckmeister.github.io
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          cd pages
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add dfauto dfsetup dfauto.ps1 dfsetup.ps1
          git commit -m "🤖 Auto-sync web installers from dotfiles@${GITHUB_SHA::7}

          Synced from: https://github.com/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA}

          This commit was automatically generated by the sync-installers workflow.
          "
          git push

      - name: Report sync status
        if: always()
        run: |
          if [ "${{ steps.check_changes.outputs.changed }}" == "true" ]; then
            echo "✅ Web installers synced successfully to buckmeister.github.io"
            echo "🔗 Live at: https://buckmeister.github.io/"
          else
            echo "ℹ️ No changes to sync (installers already up-to-date)"
          fi
